#!/bin/bash

export scriptdir=`pwd`


d=`date -u -d "-3 hours" +%Y%m%d`

fcdate=${fcdate:-$d}

export fcdate
export maxhours=48

export gradsnc=`which grads`


export publish=true
# Geometry depends on the picture Upper-leftcorner of logo with respect
# to upper-left corner of a picture 
export PUTLOGOCMD="composite  -geometry  +110+475  $scriptdir/fmi-logo-60x30a.png"
# Special logo for aqi and pollen index pictures
export PUTLOGOCMDINDEX="$PUTLOGOCMD"

export outsuff=""


export email="test-iran"
export lonrange="43.,64."
export latrange="24.,40."
export suitename="IRAN"

export OUTPUT_DIR=${scriptdir}/output-${suitename}
export domainname=Iran
